# .goreleaser.yml for HPI Mensa API
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/hpi-mensa-api/main.go
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
release:
  github:
    owner: SLH335
    name: hpi-mensa-api
nfpms:
  - id: nfpms
    file_name_template: "{{ .ConventionalFileName }}"
    package_name: hpi-mensa-api
    maintainer: SLH335
    description: An API to get data about meals at Hasso Plattner Institute and University of Potsdam
    homepage: https://github.com/RocketRene/hpi-mensa-api
    license: MIT
    formats:
      - deb
      - rpm
publishers:
  - name: fury.io
    ids:
      - nfpms
    cmd: |
      curl -F package=@{{ .ArtifactPath }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/rocketrene/
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
